---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
      ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[nginx::server]
      - recipe[cakebox]

    attributes:
      nginx:
        "skip_default_site": true
