---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
      ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[nginx::server]
      - recipe[php5-ppa]
      - recipe[phpcs]
      - recipe[cakebox]

    attributes:
      nginx:
        "skip_default_site": true
      phcs:
        "install_method": "composer"
        "coding_standards":
          "Cakephp":
              "repository": "https://github.com/cakephp/cakephp-codesniffer.git"
