---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
      ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[git-ppa]
      - recipe[percona::server]
      - recipe[percona::backup]
      - recipe[php5-ppa]
      - recipe[nginx::server]
      - recipe[composer]
      - recipe[phpcs]
      - recipe[cakebox]
    attributes:
      percona:
        "keyserver": pool.sks-keyservers.net
        "server":
          "root_password": secret
          "bind_address": 0.0.0.0
          "character_set": utf8
          "collation": utf8_unicode_ci
      nginx:
        "repository": ppa
        "skip_default_site": true
      cakebox:
        databases:
          remote_username: kitchen-user
          remote_password: kitchen-pass
